# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-19 19:06
from __future__ import unicode_literals

import Shopping__list.product.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_complete', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to=Shopping__list.product.models.product_image_path)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
